### ISSUE TITLE
Cant figure out 

### ISSUE THREAD

**Issue by pand0raQ** [gkye/DribbbleSwift#2]
Hi. Please can you describe  more detail how to extract data from dribbble, like only recent, hi definition and not animated images.
i copy past this piece in code :    

``` swift
ShotsDS.getShots(perPage: 50, list: .animated, sort: .recent){
            shotz in
            print(shotz.shots?.count)
            print(shotz.shots?[0].title)
        }
```

but thats give me Value of tuple type
`swift '(ClientReturn, [ShotsDS]?)' (aka '(ClientReturn, Optional<Array<ShotsDS>>)') has no member 'shots' error )` thanks

**Comment by gkye** [comment]
Sorry about that the documentation needs to be updated to reflect the recent changes. This code below should work

``` swift
ShotsDS.getShots(perPage: 50, list: .animated, sort: .recent){
apiData, shotz in
print(shotz?.count)
print(shotz?[0].title)
}
```

or but it hardly to read, i recomend using the first example above.

``` swift
ShotsDS.getShots(perPage: 50, list: .animated, sort: .recent){
shotz in
print(shotz.1?[0].title)
}
```
