### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by gkye** [gkye/DribbbleSwift#3]
Update docs to reflect recent changes

**Comment by pand0raQ** [comment]
i dont know how to append data to arrays or strings too((...
like that?
shotz.1?[1].title.append(self.titlexample)

thanks

**Comment by gkye** [comment]
I'm not sure what youre trying to do, could you provide more info?

**Comment by pand0raQ** [comment]
i trying to create app which should view shots ,with description and titles ,user should be able to like them, commenting etc
i have problems viewing information . i need to save commands like shotz.1?[1].title  respond into string, or, save the images urls at array . 
i try create string title , and storage there result of shotz.1?[1].title by adding .append but its not work

**Comment by gkye** [comment]
why not save the data received in array and use it according (in a collection or tableView)? The example below is using a `UICollectionView` (there's plenty of tutorials on the internet on how to use a collectionview or tableview)

``` swift
  var shots = [ShotsDS]()

//View did load or whatever your loading the data from
    ShotsDS.getShots(perPage: 50, page: page){
      data in
      if let shts = data.1{
        shts.forEach{
          self.shots.append($0)
        }
        self.collectionView?.reloadData()
      }
    }

//Collectionview 

  override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: indexPath) as! ImageCell

let url = shots[indexPath.row].images.normal
//Set your image
cell.titleLabel.text = shots[indexPath.row].title
}
```
