### ISSUE TITLE
Return Description with tags

### ISSUE THREAD

**Issue by pand0raQ** [gkye/DribbbleSwift#4]
cant figure out how to remove tags

**Comment by gkye** [comment]
Not too sure what you mean, could you explain a bit further?

**Comment by pand0raQ** [comment]
The description of shots returns with html tags like p /p , br /" .

**Comment by gkye** [comment]
Will fix this later today

**Comment by gkye** [comment]
this issue should be fixed now. run `pod update` to your project 😄
